In [1]:
!pip install numpy
!pip install gym
!pip install -e gym-zhed

In [2]:
import gym
import gym_zhed
import numpy as np
import random
import matplotlib.pyplot as plt

In [3]:
def action_to_flags(num, result=np.zeros(1024, dtype=np.int), index=0):
    if num > 1:
        action_to_flags(num // 2, result, index+1)
    result[index] = num % 2
    return result

In [4]:
state_size = 5
action_size = 1024
qtable = np.zeros((state_size, action_size))
print(f'Action size: {action_size}; State size: {state_size}')
print(qtable)

Action size: 1024; State size: 5
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
# @hyperparameters
total_episodes = 1000        # Total episodes
learning_rate = 0.01           # Learning rate
max_steps = 100               # Max steps per episode
gamma = 0.99                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.1            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [6]:
# @hyperparameters
total_episodes = 1000        # Total episodes
learning_rate = 0.01           # Learning rate
max_steps = 100               # Max steps per episode
gamma = 0.99                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.1            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

level = 1
env = gym.make('zhedContLevel' + str(level) + '-v0')
env.render()

rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    #print(f'First state: {state}')
    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
    
        if exp_exp_tradeoff > epsilon:
            val = np.argmax(qtable[state, :]) #exploitation
            action = action_to_flags(val)
        else:
            action = env.action_space.sample() #exploration
        
        new_state, reward, done, info = env.step(action) #take action and observe results
        #print(f'new_state: {new_state}; reward: {reward}; done: {done}; info: {info}')

        #updating the table using Bellman Equation
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        #cumulative rewards until now
        total_rewards = total_rewards + reward

        state = new_state
        if done == True:
            #print('Done')
            break

    episode += 1
    #reducing exploration rate
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_rewards)

print("Score over time: " +  str(sum(rewards) / total_episodes))
print(qtable)
print(epsilon)

Environment initialized
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   | 1 | G |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 

NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty direction

NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
E

Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
NOT Empty squares

Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares


NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty sq

Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !

Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squ

NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Emp

Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squ

Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares

Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty d

NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty squares
Empty squares
Empty squares
NOT Empty squares !!!
NOT Empty directions !!!
Empty square

In [7]:
state = env.reset()
step = 0
done = False
env.render()
val = np.argmax(qtable[state,:])
action = action_to_flags(val)
new_state, reward, done, info = env.step(action)

env.render()

|   |   |   |   |   |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   | 1 | G |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 

Empty squares
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   | 1 | G |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 
|   |   |   |   |   |   |   |   |   |   | 

